@ECHO OFF 
 
SET ZEROB=COPY "U:\Games\PSP\_RIPs\_RipKits\Bin\zero.file" 
 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\SYSDIR\UPDATE\DATA.BIN" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\SYSDIR\UPDATE\EBOOT.BIN" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\SYSDIR\UPDATE\PARAM.SFO" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\LANGUAGE\FRENCH.TBL" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\LANGUAGE\GERMAN.TBL" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\LANGUAGE\ITALIAN.TBL" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\LANGUAGE\JAPAN.TBL" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\LANGUAGE\KOREAN.TBL" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\LANGUAGE\SPANISH.TBL" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\FR\AUTOSAVE.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\FR\FMV_1.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\FR\FMV_2.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\FR\FMV_3.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\FR\FMV_4.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\FR\FMV_5.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\FR\FMV_6.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\FR\FMV_7.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\FR\FMV_8.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\FR\FMV_9.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\GE\AUTOSAVE.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\GE\FMV_1.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\GE\FMV_2.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\GE\FMV_3.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\GE\FMV_4.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\GE\FMV_5.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\GE\FMV_6.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\GE\FMV_7.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\GE\FMV_8.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\GE\FMV_9.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\IT\AUTOSAVE.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\IT\FMV_1.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\IT\FMV_2.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\IT\FMV_3.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\IT\FMV_4.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\IT\FMV_5.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\IT\FMV_6.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\IT\FMV_7.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\IT\FMV_8.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\IT\FMV_9.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\SP\AUTOSAVE.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\SP\FMV_1.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\SP\FMV_2.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\SP\FMV_3.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\SP\FMV_4.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\SP\FMV_5.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\SP\FMV_6.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\SP\FMV_7.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\SP\FMV_8.PMF" /Y 
%ZEROB% "U:\Games\PSP\Coded Arms - Contagion (USA) (v1.04)\PSP_GAME\USRDIR\VIDEO\SP\FMV_9.PMF" /Y 
