@ECHO OFF 
 
SET ZEROB=COPY "U:\Games\PSP\_RIPs\_RipKits\Bin\zero.file" 
 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\SYSDIR\UPDATE\DATA.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\SYSDIR\UPDATE\EBOOT.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\SYSDIR\UPDATE\PARAM.SFO" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\08003NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\08006NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\08007NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\13011NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\15000NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\15001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\15002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\22001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\22002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\32001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\32002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\32003NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\32004NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_apocal.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_athenalh.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_call.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_calliopsong.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_deathking.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_defeat.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_descent.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_epilogue.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_facingking.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_fateatlas.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_gateselys.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_keeperf.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_lastsongc.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_persinv.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_queendead.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_releaseatl.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_theduel.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_transformation.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\dx_whocalltf.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\French\game.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\08003NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\08006NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\08007NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\13011NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\15000NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\15001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\15002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\22001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\22002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\32001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\32002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\32003NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\32004NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_apocal.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_athenalh.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_call.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_calliopsong.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_deathking.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_defeat.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_descent.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_epilogue.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_facingking.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_fateatlas.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_gateselys.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_keeperf.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_lastsongc.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_persinv.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_queendead.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_releaseatl.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_theduel.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_transformation.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\dx_whocalltf.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\German\game.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\08003NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\08006NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\08007NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\13011NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\15000NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\15001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\15002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\22001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\22002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\32001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\32002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\32003NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\32004NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_apocal.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_athenalh.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_call.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_calliopsong.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_deathking.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_defeat.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_descent.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_epilogue.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_facingking.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_fateatlas.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_gateselys.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_keeperf.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_lastsongc.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_persinv.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_queendead.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_releaseatl.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_theduel.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_transformation.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\dx_whocalltf.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Italian\game.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\08003NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\08006NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\08007NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\13011NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\15000NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\15001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\15002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\22001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\22002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\32001NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\32002NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\32003NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\32004NA.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_apocal.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_athenalh.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_call.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_calliopsong.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_deathking.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_defeat.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_descent.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_epilogue.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_facingking.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_fateatlas.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_gateselys.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_keeperf.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_lastsongc.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_persinv.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_queendead.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_releaseatl.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_theduel.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_transformation.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\dx_whocalltf.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\Spanish\game.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_3_eos_chamber_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_3_eos_chamber_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_3_eos_chamber_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_3_eos_chamber_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_5_parry_challenge_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_5_parry_challenge_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_5_parry_challenge_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_5_parry_challenge_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_6_exit_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_6_exit_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_6_exit_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ec_6_exit_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_01_fields_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_01_fields_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_01_fields_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_01_fields_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_03_crash_landing_2_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_03_crash_landing_2_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_03_crash_landing_2_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_03_crash_landing_2_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_03_crash_landing_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_03_crash_landing_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_03_crash_landing_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ef_03_crash_landing_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ht13_astrolabe_high_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ht13_astrolabe_high_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ht13_astrolabe_high_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ht13_astrolabe_high_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ht18_astrolabe_final_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ht18_astrolabe_final_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ht18_astrolabe_final_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\ht18_astrolabe_final_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_01_rock_climb_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_01_rock_climb_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_01_rock_climb_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_01_rock_climb_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_02_village_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_02_village_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_02_village_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_02_village_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_05_steed_return_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_05_steed_return_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_05_steed_return_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\mar_05_steed_return_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_bath_house_01_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_bath_house_01_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_bath_house_01_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_bath_house_01_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_00_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_00_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_00_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_00_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_01_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_01_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_01_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_01_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_02_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_02_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_02_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_beach_02_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_city_streets_01_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_city_streets_01_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_city_streets_01_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_city_streets_01_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_city_wall_02_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_city_wall_02_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_city_wall_02_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_city_wall_02_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_king_fight_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_king_fight_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_king_fight_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\pi_king_fight_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\poh_persephone_chamber_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\poh_persephone_chamber_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\poh_persephone_chamber_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\poh_persephone_chamber_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\tar_caves_01_welcomepar_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\tar_caves_01_welcomepar_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\tar_caves_01_welcomepar_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\tar_caves_01_welcomepar_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\tar_caves_03_arenacaver_fre.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\tar_caves_03_arenacaver_ger.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\tar_caves_03_arenacaver_ita.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\data\tar_caves_03_arenacaver_spa.bin" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\08003NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\08006NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\08007NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\13011NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\15000NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\15001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\15002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\22001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\22002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\32001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\32002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\32003NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\French\32004NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\08003NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\08006NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\08007NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\13011NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\15000NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\15001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\15002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\22001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\22002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\32001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\32002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\32003NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\German\32004NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\08003NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\08006NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\08007NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\13011NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\15000NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\15001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\15002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\22001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\22002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\32001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\32002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\32003NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Italian\32004NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\08003NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\08006NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\08007NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\13011NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\15000NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\15001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\15002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\22001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\22002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\32001NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\32002NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\32003NA.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War Chains of Olympus (EUR)\PSP_GAME\USRDIR\dialogs\Spanish\32004NA.AT3" /Y 
