@ECHO OFF 
 
SET ZEROB=COPY "U:\Games\PSP\_RIPs\_RipKits\Bin\zero.file" 
 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\SYSDIR\UPDATE\DATA.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\SYSDIR\UPDATE\EBOOT.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\SYSDIR\UPDATE\PARAM.SFO" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASH_010_WRECK_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASH_010_WRECK_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASH_020_TOWN_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASH_020_TOWN_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASH_040_CAVE_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASH_040_CAVE_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASH_050_PUZZLE_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASH_050_PUZZLE_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASH_080_PATH_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASH_080_PATH_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASR_020_ARENA_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ASR_020_ARENA_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATB_030_VISTA_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATB_030_VISTA_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATB_090_ENTRANCE1_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATB_090_ENTRANCE1_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATB_130_LANAEUS_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATB_130_LANAEUS_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_010_STERN_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_010_STERN_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_020_BOW_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_020_BOW_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_060_CAVES_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_060_CAVES_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_080_BALCONIES_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_080_BALCONIES_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_120_APPROACH_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_120_APPROACH_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_130_HOME_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ATT_130_HOME_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\BRT_020_CYCLOPS_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\BRT_020_CYCLOPS_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\BRT_070_COURTYARD_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\BRT_070_COURTYARD_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\BRT_095_GRAVEDIGGER_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\BRT_095_GRAVEDIGGER_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\BRT_110_PROJECTS_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\BRT_110_PROJECTS_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_040_COURTYARD_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_040_COURTYARD_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_050_REVEAL_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_050_REVEAL_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_060_ROPE_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_060_ROPE_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_100_FIRE_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_100_FIRE_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_120_DEIMOS_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_120_DEIMOS_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_130_FALL_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\DTH_130_FALL_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ICE_010_BRIDGE_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ICE_010_BRIDGE_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ICE_015_SPARTAN_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ICE_015_SPARTAN_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ICE_040_QUARY_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ICE_040_QUARY_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ICE_120_DAUGHTER_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ICE_120_DAUGHTER_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ICR_050_CAVEFIGHT_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\ICR_050_CAVEFIGHT_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\PAS_010_GRIND_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\PAS_010_GRIND_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\PAS_030_RIVER_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\PAS_030_RIVER_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\PAS_050_MIDAS_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\PAS_050_MIDAS_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\PAS_100_CLIMB_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\PAS_100_CLIMB_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\ARENA.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\ATTVO1EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\ATTVO2EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\CHALLENGE.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\DTHVO1EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\DTHVO2EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\FRONTEND.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\GAME.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_ASH.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_ASR.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_ATB.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_ATT.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_BRT.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_DTH.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_ICE.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_ICR.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_PAS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_SCB.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_SPR.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_VOL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_VTX.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\LEVELS_ZT.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\NIS_ATT_130_POSEIDON.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\NIS_DTH_040_THANATOS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\NIS_DTH_130_FALL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\NIS_ICE_010_DAUGHTER.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\NIS_ICE_040_DAUGHTERVICTIM.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\NIS_PAS_010_POSSESSED.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\NIS_SPA_130_ARES.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\NIS_SPA_130_STATUE.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\NIS_SPA_160_SPEAR.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_BATTLEGROUND.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_BETRAYL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_BOATRIDE.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_BROTHER.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_BROTHERS_IN_ARMS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_CONCLUSION.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_DAUGHTER_OF_DEATH.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_DEADMOTHER.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_DEIMOS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_DROWNING.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_ENDOFATLANTIS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_EPILOGUE.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_FALLOFABRO.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_FINALCONF.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_FMIDAS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_GRAVEDIG.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_INTRO.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_MARKW.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_MEETD.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_PRIDE_OSP.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_SEPARATION.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_SONOFZEUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_THERA.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_TRUTHREV.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\R6_WOATHENA.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\SPAVO1EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\SPAVO2EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\POLISH\ZTVO1EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\ARENA.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\ATTVO1EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\ATTVO2EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\CHALLENGE.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\DTHVO1EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\DTHVO2EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\FRONTEND.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\GAME.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_ASH.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_ASR.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_ATB.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_ATT.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_BRT.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_DTH.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_ICE.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_ICR.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_PAS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_SCB.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_SPR.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_VOL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_VTX.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\LEVELS_ZT.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\NIS_ATT_130_POSEIDON.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\NIS_DTH_040_THANATOS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\NIS_DTH_130_FALL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\NIS_ICE_010_DAUGHTER.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\NIS_ICE_040_DAUGHTERVICTIM.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\NIS_PAS_010_POSSESSED.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\NIS_SPA_130_ARES.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\NIS_SPA_130_STATUE.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\NIS_SPA_160_SPEAR.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_BATTLEGROUND.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_BETRAYL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_BOATRIDE.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_BROTHER.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_BROTHERS_IN_ARMS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_CONCLUSION.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_DAUGHTER_OF_DEATH.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_DEADMOTHER.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_DEIMOS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_DROWNING.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_ENDOFATLANTIS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_EPILOGUE.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_FALLOFABRO.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_FINALCONF.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_FMIDAS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_GRAVEDIG.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_INTRO.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_MARKW.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_MEETD.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_PRIDE_OSP.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_SEPARATION.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_SONOFZEUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_THERA.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_TRUTHREV.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\R6_WOATHENA.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\SPAVO1EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\SPAVO2EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\RUSSIAN\ZTVO1EN.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_010_CLIMB_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_010_CLIMB_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_015_WALK_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_015_WALK_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_020_ARENA_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_020_ARENA_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_030_DEATH_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_030_DEATH_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_040_STALK_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_040_STALK_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_050_CARRY_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SCB_050_CARRY_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_010_LANDING_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_010_LANDING_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_020_STREETS_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_020_STREETS_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_030_STAIRS_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_030_STAIRS_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_035_SEX_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_035_SEX_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_040_HOME_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_040_HOME_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_043_KIDFIGHT_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_043_KIDFIGHT_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_045_HOLE_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_045_HOLE_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_050_PRISON_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_050_PRISON_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_060_LION_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_060_LION_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_070_SUPPORTER_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_070_SUPPORTER_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_075_CRUSHERS_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_075_CRUSHES_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_130_STATUE_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_130_STATUE_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_145_MIRROR_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_145_MIRROR_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_160_EXIT_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\SPA_160_EXIT_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VOL_010_FISSURE_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VOL_010_FISSURE_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VOL_030_FIREBLADES_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VOL_030_FIREBLADES_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VOL_035_TITAN_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VOL_035_TITAN_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VOL_050_AQUEDUCT_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VOL_050_AQUEDUCT_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VOL_060_HUB_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VOL_060_HUB_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VTX_020_DOCK_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VTX_020_DOCK_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VTX_030_BOAT_POL.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DATA\VTX_030_BOAT_RUS.BIN" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\POLISH\ATTVO1EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\POLISH\ATTVO2EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\POLISH\DTHVO1EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\POLISH\DTHVO2EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\POLISH\SPAVO1EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\POLISH\SPAVO2EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\POLISH\ZTVO1EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\RUSSIAN\ATTVO1EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\RUSSIAN\ATTVO2EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\RUSSIAN\DTHVO1EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\RUSSIAN\DTHVO2EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\RUSSIAN\SPAVO1EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\RUSSIAN\SPAVO2EN.AT3" /Y 
%ZEROB% "U:\Games\PSP\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01)\PSP_GAME\USRDIR\DIALOGS\RUSSIAN\ZTVO1EN.AT3" /Y 
