@ECHO OFF 
 
SET ZEROB=COPY "U:\Games\PSP\_RIPs\_RipKits\Bin\zero.file" 
 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\SYSDIR\UPDATE\DATA.BIN" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\SYSDIR\UPDATE\EBOOT.BIN" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\SYSDIR\UPDATE\PARAM.SFO" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\bonus_ch.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\bonus_sk.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\boot.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\game_ch.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\game_demo.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\game_net.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\game_pz.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\game_si.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\game_ta.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\game_vc.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\game_vm.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\logo.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\menu.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin01_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin01_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin02_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin02_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin03_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin03_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin04_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin04_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin05_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin05_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin06_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin06_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin07_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin07_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin08_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin08_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin09_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin09_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin101_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin101_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin102_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin102_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin103_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin103_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin104_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin104_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin105_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin105_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin106_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin106_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin107_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin107_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin108_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin108_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin109_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin109_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin10_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin10_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin110_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin110_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin11_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin11_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin12_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin12_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin13_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin13_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin14_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin14_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin15_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin15_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin16_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin16_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin17_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin17_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin18_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin18_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin19_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin19_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin201_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin202_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin203_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin204_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin205_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin206_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin207_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin208_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin209_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin20_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin20_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin210_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin211_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin212_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin213_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin214_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin215_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin216_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin217_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin218_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin219_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin21_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin21_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin220_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin221_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin222_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin223_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin224_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin225_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin226_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin22_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin22_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin23_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin23_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin24_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin24_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin301_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin302_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin303_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin304_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin401_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin401_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin402_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin402_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin403_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin403_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin404_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin404_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin405_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin405_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin406_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\skin\skin406_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\staffroll.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\fr\title.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\bonus_ch.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\bonus_sk.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\boot.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\game_ch.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\game_demo.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\game_net.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\game_pz.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\game_si.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\game_ta.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\game_vc.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\game_vm.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\logo.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\menu.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin01_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin01_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin02_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin02_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin03_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin03_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin04_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin04_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin05_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin05_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin06_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin06_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin07_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin07_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin08_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin08_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin09_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin09_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin101_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin101_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin102_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin102_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin103_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin103_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin104_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin104_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin105_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin105_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin106_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin106_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin107_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin107_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin108_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin108_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin109_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin109_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin10_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin10_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin110_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin110_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin11_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin11_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin12_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin12_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin13_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin13_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin14_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin14_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin15_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin15_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin16_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin16_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin17_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin17_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin18_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin18_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin19_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin19_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin201_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin202_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin203_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin204_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin205_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin206_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin207_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin208_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin209_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin20_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin20_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin210_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin211_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin212_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin213_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin214_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin215_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin216_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin217_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin218_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin219_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin21_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin21_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin220_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin221_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin222_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin223_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin224_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin225_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin226_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin22_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin22_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin23_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin23_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin24_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin24_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin301_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin302_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin303_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin304_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin401_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin401_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin402_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin402_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin403_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin403_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin404_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin404_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin405_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin405_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin406_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\skin\skin406_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\staffroll.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\ge\title.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\bonus_ch.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\bonus_sk.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\boot.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\game_ch.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\game_demo.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\game_net.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\game_pz.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\game_si.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\game_ta.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\game_vc.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\game_vm.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\logo.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\menu.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin01_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin01_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin02_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin02_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin03_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin03_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin04_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin04_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin05_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin05_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin06_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin06_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin07_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin07_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin08_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin08_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin09_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin09_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin101_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin101_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin102_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin102_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin103_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin103_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin104_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin104_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin105_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin105_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin106_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin106_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin107_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin107_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin108_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin108_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin109_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin109_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin10_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin10_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin110_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin110_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin11_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin11_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin12_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin12_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin13_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin13_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin14_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin14_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin15_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin15_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin16_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin16_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin17_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin17_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin18_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin18_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin19_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin19_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin201_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin202_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin203_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin204_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin205_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin206_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin207_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin208_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin209_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin20_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin20_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin210_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin211_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin212_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin213_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin214_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin215_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin216_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin217_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin218_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin219_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin21_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin21_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin220_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin221_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin222_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin223_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin224_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin225_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin226_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin22_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin22_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin23_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin23_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin24_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin24_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin301_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin302_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin303_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin304_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin401_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin401_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin402_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin402_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin403_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin403_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin404_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin404_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin405_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin405_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin406_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\skin\skin406_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\staffroll.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\it\title.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\bonus_ch.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\bonus_sk.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\boot.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\game_ch.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\game_demo.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\game_net.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\game_pz.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\game_si.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\game_ta.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\game_vc.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\game_vm.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\logo.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\menu.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin01_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin01_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin02_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin02_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin03_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin03_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin04_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin04_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin05_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin05_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin06_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin06_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin07_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin07_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin08_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin08_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin09_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin09_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin101_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin101_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin102_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin102_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin103_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin103_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin104_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin104_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin105_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin105_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin106_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin106_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin107_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin107_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin108_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin108_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin109_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin109_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin10_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin10_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin110_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin110_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin11_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin11_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin12_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin12_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin13_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin13_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin14_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin14_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin15_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin15_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin16_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin16_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin17_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin17_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin18_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin18_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin19_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin19_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin201_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin202_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin203_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin204_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin205_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin206_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin207_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin208_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin209_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin20_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin20_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin210_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin211_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin212_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin213_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin214_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin215_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin216_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin217_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin218_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin219_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin21_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin21_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin220_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin221_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin222_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin223_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin224_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin225_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin226_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin22_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin22_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin23_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin23_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin24_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin24_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin301_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin302_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin303_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin304_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin401_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin401_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin402_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin402_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin403_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin403_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin404_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin404_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin405_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin405_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin406_1p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\skin\skin406_2p.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\staffroll.dat" /Y 
%ZEROB% "U:\Games\PSP\Lumines (Europe) (En,Fr,De,Es,It) (v1.01)\PSP_GAME\USRDIR\lang\sp\title.dat" /Y 
