@ECHO OFF 
 
SET ZEROB=COPY "U:\Games\PSP\_RIPs\_RipKits\Bin\zero.file" 
 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\SYSDIR\UPDATE\DATA.BIN" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\SYSDIR\UPDATE\EBOOT.BIN" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\SYSDIR\UPDATE\PARAM.SFO" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\GLOBAL\GAME_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\GLOBAL\GAME_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\GLOBAL\GAME_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\GLOBAL\GAME_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A01_ES\A01_ES_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A01_ES\A01_ES_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A01_ES\A01_ES_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A01_ES\A01_ES_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A02_TH\A02_TH_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A02_TH\A02_TH_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A02_TH\A02_TH_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A02_TH\A02_TH_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A03_NE\A03_NE_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A03_NE\A03_NE_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A03_NE\A03_NE_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A03_NE\A03_NE_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A04_SM\A04_SM_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A04_SM\A04_SM_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A04_SM\A04_SM_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A04_SM\A04_SM_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A06_CI\A06_CI_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A06_CI\A06_CI_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A06_CI\A06_CI_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A06_CI\A06_CI_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A07_2T\A07_2T_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A07_2T\A07_2T_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A07_2T\A07_2T_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A07_2T\A07_2T_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A07_TO\A07_TO_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A07_TO\A07_TO_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A07_TO\A07_TO_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A07_TO\A07_TO_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A09_BU\A09_BU_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A09_BU\A09_BU_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A09_BU\A09_BU_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A09_BU\A09_BU_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A10_BR\A10_BR_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A10_BR\A10_BR_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A10_BR\A10_BR_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A10_BR\A10_BR_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A11_ME\A11_ME_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A11_ME\A11_ME_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A11_ME\A11_ME_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A11_ME\A11_ME_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A12_PL\A12_PL_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A12_PL\A12_PL_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A12_PL\A12_PL_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A12_PL\A12_PL_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A14_SU\A14_SU_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A14_SU\A14_SU_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A14_SU\A14_SU_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A14_SU\A14_SU_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A15_CE\A15_CE_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A15_CE\A15_CE_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A15_CE\A15_CE_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A15_CE\A15_CE_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A16_TV\A16_TV_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A16_TV\A16_TV_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A16_TV\A16_TV_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A16_TV\A16_TV_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A17_CR\A17_CR_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A17_CR\A17_CR_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A17_CR\A17_CR_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A17_CR\A17_CR_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A18_MA\A18_MA_F.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A18_MA\A18_MA_G.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A18_MA\A18_MA_I.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\LEVELS\A18_MA\A18_MA_S.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A01_ES_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A01_ES_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A01_ES_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A01_ES_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A02_TH_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A02_TH_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A02_TH_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A02_TH_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A02_TH_O\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A02_TH_O\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A02_TH_O\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A02_TH_O\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A03_NE_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A03_NE_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A03_NE_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A03_NE_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A03_NE_O\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A03_NE_O\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A03_NE_O\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A03_NE_O\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A04_SM_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A04_SM_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A04_SM_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A04_SM_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A04_SM_O\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A04_SM_O\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A04_SM_O\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A04_SM_O\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A06_CI_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A06_CI_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A06_CI_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A06_CI_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A07_TO_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A07_TO_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A07_TO_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A07_TO_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A09_BU_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A09_BU_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A09_BU_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A09_BU_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A10_BR_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A10_BR_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A10_BR_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A10_BR_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A10_BR_O\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A10_BR_O\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A10_BR_O\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A10_BR_O\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A11_ME_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A11_ME_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A11_ME_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A11_ME_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A11_ME_O\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A11_ME_O\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A11_ME_O\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A11_ME_O\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A12_PL_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A12_PL_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A12_PL_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A12_PL_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A14_SU_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A14_SU_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A14_SU_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A14_SU_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A15_CE_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A15_CE_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A15_CE_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A15_CE_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A15_CE_O\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A15_CE_O\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A15_CE_O\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A15_CE_O\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A16_TV_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A16_TV_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A16_TV_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A16_TV_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A17_CR_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A17_CR_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A17_CR_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A17_CR_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A17_CR_O\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A17_CR_O\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A17_CR_O\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A17_CR_O\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A18_MA_I\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A18_MA_I\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A18_MA_I\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A18_MA_I\SPA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A18_MA_O\FRE.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A18_MA_O\GER.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A18_MA_O\ITA.GXT" /Y 
%ZEROB% "U:\Games\PSP\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02)\PSP_GAME\USRDIR\MOVIES\SUBS\A18_MA_O\SPA.GXT" /Y 
