@ECHO OFF 
 
SET ZEROB=COPY "U:\Games\PSP\_RIPs\_RipKits\Bin\zero.file" 
 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\SYSDIR\UPDATE\DATA.BIN" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\SYSDIR\UPDATE\EBOOT.BIN" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\SYSDIR\UPDATE\PARAM.SFO" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\frontend\backendscreens\pausemenufrench.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\frontend\backendscreens\pausemenugerman.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\frontend\backendscreens\pausemenuitalian.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\frontend\backendscreens\pausemenuspanish.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\frontend\fronta.bun" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\global\globala.bun" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\global\ingamea.bun" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\hud\hudfrench.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\hud\hudgerman.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\hud\huditalian.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\hud\hudjapanese.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\hud\hudspanish.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\hud\loadingbootup_jp.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\french.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\german.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\italian.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\japanese.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\spanish.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\trc\be2fe\french.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\trc\be2fe\german.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\trc\be2fe\italian.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\trc\be2fe\japanese.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\trc\be2fe\spanish.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\trc\fe2be\french.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\trc\fe2be\german.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\trc\fe2be\italian.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\trc\fe2be\japanese.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\locale\trc\fe2be\spanish.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_fr_1.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_fr_2.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_fr_3.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_fr_4.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_gr_1.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_gr_2.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_gr_3.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_gr_4.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_it_1.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_it_2.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_it_3.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_it_4.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_jp_1.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_jp_2.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_jp_3.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_jp_4.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_sp_1.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_sp_2.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_sp_3.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\sound\mostwanted\mw_speech_sp_4.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\video\eag_french.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\video\eag_german.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\video\eag_italian.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\video\eag_spanish.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\video\extras1_fr.pmf" /Y 
