@ECHO OFF 
 
SET ZEROB=COPY "U:\Games\PSP\_RIPs\_RipKits\Bin\zero.file" 
 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\SYSDIR\UPDATE\DATA.BIN" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\SYSDIR\UPDATE\EBOOT.BIN" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\SYSDIR\UPDATE\PARAM.SFO" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\compareheapbe.csv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\compareheapfe.csv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\global\globala.bun" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\global\ingamea.bun" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy1\hudczech.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy1\huddutch.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy1\hudfrench.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy1\hudgerman.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy1\hudhungarian.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy1\huditalian.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy1\hudpolish.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy1\hudrussian.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy1\hudspanish.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy2\hudczech.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy2\huddutch.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy2\hudfrench.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy2\hudgerman.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy2\hudhungarian.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy2\huditalian.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy2\hudpolish.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy2\hudrussian.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\hud\copy2\hudspanish.viv" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\czech.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\dutch.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\french.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\german.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\hungarian.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\italian.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\polish.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\russian.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\spanish.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\cht_cn.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\cze_cz.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\dut_nl.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\cht_cn.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\cze_cz.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\dut_nl.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\fre_fr.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\ger_de.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\hun_hu.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\ita_it.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\jpn_jp.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\kor_kr.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\pol_pl.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\por_pt.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\rus_ru.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\spa_es.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fe2be\spa_mx.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\fre_fr.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\ger_de.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\hun_hu.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\ita_it.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\jpn_jp.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\kor_kr.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\pol_pl.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\por_pt.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\rus_ru.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\spa_es.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\locale\trc\spa_mx.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\netcore\locale\czech.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\netcore\locale\dutch.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\netcore\locale\french.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\netcore\locale\german.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\netcore\locale\hungarian.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\netcore\locale\italian.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\netcore\locale\polish.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\netcore\locale\russian.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\netcore\locale\spanish.loc" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_03_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_03_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_03_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_03_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_03_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_04_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_04_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_04_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_04_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_04_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_05_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_05_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_05_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_05_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_05_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_06_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_06_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_06_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_06_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_06_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_07_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_07_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_07_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_07_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_07_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_08_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_08_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_08_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_08_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\chasedownmission_08_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cism_cism_00_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cism_cism_00_fr.ast" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cism_cism_00_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cism_cism_00_gr.ast" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cism_cism_00_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cism_cism_00_it.ast" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cism_cism_00_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cism_cism_00_ru.ast" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cism_cism_00_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cism_cism_00_sp.ast" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_03_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_03_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_03_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_03_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_03_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_04_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_04_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_04_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_04_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_04_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_05_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_05_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_05_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_05_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_05_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_06_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_06_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_06_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_06_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_06_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_07_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_07_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_07_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_07_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_07_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_08_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_08_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_08_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_08_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_chasedown_08_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_00_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_00_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_00_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_00_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_00_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_03_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_03_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_03_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_03_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops1_03_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_00_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_00_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_00_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_00_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_00_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_03_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_03_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_03_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_03_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops2_03_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_00_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_00_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_00_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_00_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_00_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_03_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_03_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_03_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_03_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops3_03_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_00_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_00_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_00_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_00_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_00_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_03_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_03_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_03_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_03_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_cops4_03_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_03_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_03_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_03_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_03_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_03_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_04_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_04_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_04_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_04_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_04_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_05_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_05_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_05_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_05_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_05_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_06_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_06_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_06_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_06_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_06_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_07_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_07_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_07_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_07_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_07_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_08_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_08_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_08_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_08_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\cops_hotcar_08_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_00_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_00_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_00_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_00_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_00_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_03_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_03_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_03_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_03_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_03_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_04_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_04_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_04_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_04_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_04_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_05_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_05_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_05_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_05_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_05_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_06_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_06_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_06_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_06_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_06_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_07_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_07_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_07_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_07_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_07_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_08_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_08_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_08_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_08_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_chasedown_08_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_03_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_03_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_03_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_03_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_03_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_04_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_04_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_04_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_04_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_04_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_05_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_05_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_05_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_05_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_05_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_06_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_06_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_06_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_06_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_06_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_07_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_07_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_07_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_07_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_07_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_08_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_08_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_08_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_08_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\dispatch_hotcar_08_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_01_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_01_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_01_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_01_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_01_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_02_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_02_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_02_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_02_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_02_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_03_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_03_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_03_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_03_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_03_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_04_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_04_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_04_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_04_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_04_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_05_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_05_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_05_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_05_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_05_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_06_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_06_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_06_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_06_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_06_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_07_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_07_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_07_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_07_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_07_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_08_fr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_08_gr.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_08_it.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_08_ru.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\sound\speech\hotcarmissionspeech_08_sp.abk" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\eag_french.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\eag_spanish.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_00_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_00_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_00_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_01_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_01_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_01_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_02_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_02_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_02_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_03_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_03_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_03_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_04_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_04_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_04_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_05_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_05_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_05_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_06_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_06_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_06_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_07_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_07_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_07_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_08_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_08_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_08_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_09_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_09_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_09_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_10_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_10_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_10_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_11_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_11_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_11_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_12_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_12_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_12_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_13_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_13_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_13_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_14_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_14_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_14_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_15_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_15_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_15_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_16_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_16_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_16_sp.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_17_fr.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_17_ru.pmf" /Y 
%ZEROB% "U:\Games\PSP\Need for Speed - Undercover (USA)\PSP_GAME\USRDIR\video\video_17_sp.pmf" /Y 
