@ECHO OFF 
 
SET ZEROB=COPY "U:\Games\PSP\_RIPs\_RipKits\Bin\zero.file" 
 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\SYSDIR\UPDATE\DATA.BIN" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\SYSDIR\UPDATE\EBOOT.BIN" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\SYSDIR\UPDATE\PARAM.SFO" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\EXTRAMESSAGES.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\GSPS2.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\MENU.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\SGPS2.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\SVNMS.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\SVPTS.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\T100.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\T110.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\T200.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\T300.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\T310.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\T320.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\T400.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\T610.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\TE.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\TFI.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\TSG.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\TSK.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\TSPC.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\EU\TWC.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\FONTS\POP3_24.MFT" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\P3COMMON.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\P3INGAME.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\FRENCH\P3MAIN.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\EXTRAMESSAGES.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\GSPS2.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\MENU.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\SGPS2.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\SVNMS.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\SVPTS.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\T100.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\T110.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\T200.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\T300.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\T310.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\T320.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\T400.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\T610.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\TE.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\TFI.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\TSG.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\TSK.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\TSPC.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\EU\TWC.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\FONTS\POP3_24.MFT" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\P3COMMON.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\P3INGAME.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\GERMAN\P3MAIN.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\EXTRAMESSAGES.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\GSPS2.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\MENU.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\SGPS2.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\SVNMS.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\SVPTS.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\T100.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\T110.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\T200.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\T300.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\T310.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\T320.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\T400.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\T610.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\TE.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\TFI.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\TSG.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\TSK.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\TSPC.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\EU\TWC.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\FONTS\POP3_24.MFT" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\P3COMMON.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\P3INGAME.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\ITALIAN\P3MAIN.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\EXTRAMESSAGES.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\GSPS2.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\MENU.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\SGPS2.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\SVNMS.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\SVPTS.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\T100.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\T110.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\T200.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\T300.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\T310.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\T320.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\T400.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\T610.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\TE.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\TFI.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\TSG.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\TSK.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\TSPC.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\EU\TWC.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\FONTS\POP3_24.MFT" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\P3COMMON.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\P3INGAME.MGB" /Y 
%ZEROB% "U:\Games\PSP\Prince of Persia Rival Swords (EUR)\PSP_GAME\USRDIR\MENU\SPANISH\P3MAIN.MGB" /Y 
