@ECHO OFF 
 
SET ZEROB=COPY "U:\Games\PSP\_RIPs\_RipKits\Bin\zero.file" 
 
%ZEROB% "U:\Games\PSP\Spider-Man 3 (USA) (v1.02)\PSP_GAME\SYSDIR\UPDATE\DATA.BIN" /Y 
%ZEROB% "U:\Games\PSP\Spider-Man 3 (USA) (v1.02)\PSP_GAME\SYSDIR\UPDATE\EBOOT.BIN" /Y 
%ZEROB% "U:\Games\PSP\Spider-Man 3 (USA) (v1.02)\PSP_GAME\SYSDIR\UPDATE\PARAM.SFO" /Y 
