@ECHO OFF 
 
SET ZEROB=COPY "U:\Games\PSP\_RIPs\_RipKits\Bin\zero.file" 
 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\SYSDIR\UPDATE\DATA.BIN" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\SYSDIR\UPDATE\EBOOT.BIN" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\SYSDIR\UPDATE\PARAM.SFO" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\COMMON\STRINGS_F.DAT" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\COMMON\STRINGS_G.DAT" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\COMMON\STRINGS_I.DAT" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\COMMON\STRINGS_S.DAT" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.1.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.1.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.1.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.1.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.1.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.1.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.1.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.1.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.2.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.2.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.2.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.2.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.2.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.2.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.2.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.2.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.3.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.3.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.3.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.3.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.3.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.3.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.3.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\FRENCH\40.3.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.1.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.1.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.1.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.1.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.1.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.1.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.1.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.1.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.2.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.2.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.2.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.2.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.2.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.2.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.2.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.2.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.3.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.3.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.3.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.3.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.3.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.3.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.3.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\GERMAN\40.3.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.1.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.1.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.1.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.1.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.1.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.1.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.1.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.1.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.2.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.2.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.2.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.2.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.2.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.2.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.2.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.2.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.3.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.3.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.3.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.3.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.3.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.3.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.3.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\ITALIAN\40.3.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.1.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.1.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.1.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.1.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.1.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.1.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.1.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.1.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.2.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.2.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.2.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.2.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.2.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.2.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.2.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.2.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.3.1.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.3.1.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.3.1.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.3.1.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.3.2.1.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.3.2.2.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.3.2.3.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\FRONTEND\RATINGS_VO\SPANISH\40.3.2.4.AT3" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\GAMESHARE\UPLOAD_F" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\GAMESHARE\UPLOAD_G" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\GAMESHARE\UPLOAD_I" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\GAMESHARE\UPLOAD_S" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DEATHMATCH_B\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DEATHMATCH_B\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DEATHMATCH_B\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DEATHMATCH_B\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DEATHMATCH_B\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DEATHMATCH_B\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DEATHMATCH_B\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DEATHMATCH_B\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\UNFREED_OBJ_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\UNFREED_OBJ_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\UNFREED_OBJ_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\UNFREED_OBJ_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\VOLATILE_OBJ_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\VOLATILE_OBJ_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\VOLATILE_OBJ_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\VOLATILE_OBJ_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\DETROIT\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\UNFREED_OBJ_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\UNFREED_OBJ_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\UNFREED_OBJ_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\UNFREED_OBJ_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\VOLATILE_OBJ_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\VOLATILE_OBJ_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\VOLATILE_OBJ_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\VOLATILE_OBJ_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\REFINERY\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\UNFREED_OBJ_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\UNFREED_OBJ_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\UNFREED_OBJ_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\UNFREED_OBJ_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\VOLATILE_OBJ_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\VOLATILE_OBJ_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\VOLATILE_OBJ_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\VOLATILE_OBJ_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\SHANTY\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\UNFREED_OBJ_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\UNFREED_OBJ_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\UNFREED_OBJ_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\UNFREED_OBJ_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\VOLATILE_OBJ_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\VOLATILE_OBJ_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\VOLATILE_OBJ_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\VOLATILE_OBJ_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\MULTI\WEAPONS\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_A1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_A1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_A1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_A1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_A1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_A1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_A1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_A1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_B1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_B1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_B1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_B1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_B1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_B1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_B1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_B1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C3\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C3\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C3\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C3\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C3\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C3\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C3\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C3\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C4\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C4\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C4\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C4\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C4\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C4\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C4\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\AERO_1P\AERO_C4\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A2\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A2\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A2\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A2\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A2\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A2\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A2\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\CASIN_1P\CASIN_A2\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_A1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_A1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_A1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_A1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_A1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_A1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_A1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_A1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_B1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_B1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_B1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_B1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_B1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_B1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_B1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\HKONG_1P\HKONG_B1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\NARBO_1P\NARBO_A1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\NARBO_1P\NARBO_A1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\NARBO_1P\NARBO_A1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\NARBO_1P\NARBO_A1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\NARBO_1P\NARBO_A1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\NARBO_1P\NARBO_A1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\NARBO_1P\NARBO_A1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\NARBO_1P\NARBO_A1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A2\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A2\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A2\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A2\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A2\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A2\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A2\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_A2\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B2\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B2\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B2\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B2\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B2\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B2\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B2\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B2\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B3\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B3\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B3\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B3\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B3\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B3\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B3\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_B3\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_C1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_C1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_C1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_C1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_C1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_C1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_C1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_C1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D2\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D2\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D2\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D2\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D2\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D2\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D2\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_D2\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_F1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_F1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_F1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_F1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_F1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_F1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_F1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\REFIN_1P\REFIN_F1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_A1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_A1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_A1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_A1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_A1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_A1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_A1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_A1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_B1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_B1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_B1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_B1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_B1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_B1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_B1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\SHANT_1P\SHANT_B1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_2\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_2\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_2\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_2\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_2\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_2\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_2\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_2\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_3\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_3\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_3\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_3\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_3\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_3\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_3\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_3\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_6\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_6\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_6\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_6\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_6\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_6\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_6\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_6\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_7\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_7\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_7\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_7\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_7\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_7\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_7\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_7\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_8\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_8\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_8\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_8\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_8\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_8\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_8\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\TRAIN_1P\TRAIN_8\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A2\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A2\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A2\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A2\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A2\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A2\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A2\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_A2\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_C1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_C1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_C1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_C1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_C1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_C1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_C1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_C1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_D1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_D1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_D1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_D1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_D1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_D1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_D1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\WEPPL_1P\WEPPL_D1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A1\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A1\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A1\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A1\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A1\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A1\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A1\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A1\VOLATILE_S.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A2\UNFREED_F.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A2\UNFREED_G.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A2\UNFREED_I.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A2\UNFREED_S.HGZ" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A2\VOLATILE_F.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A2\VOLATILE_G.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A2\VOLATILE_I.HOG" /Y 
%ZEROB% "U:\Games\PSP\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It)\PSP_GAME\USRDIR\GAMEDATA\SINGLE\ZUGSP_1P\ZUGSP_A2\VOLATILE_S.HOG" /Y 
