@ECHO OFF

ECHO . > "G:\Games\PSP\_ISO\Capcom Classics Collection Remixed (USA).ISO.txt"
ECHO . > "G:\Games\PSP\_ISO\Chessmaster-The Art of Learning (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Coded Arms - Contagion (USA) (v1.04).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Coded Arms (En,Ja) (v1.01) [b].iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Colin McRae - DiRT 2 (USA) (v1.02).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Colin McRae Rally 2005 Plus REPACK (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Dave Mirra BMX Challenge (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Dead to Rights - Reckoning (Europe) (En,Fr,De,Es,It) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Def Jam - Fight for NY - The Takeover (Europe).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Disgaea Infinite (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\DJ MAX Portable 3 (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Driver 76 (Europe) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Dynasty Warriors - Strikeforce (Europe) (En,Fr,De).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Dynasty Warriors (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Dynasty Warriors Vol. 2 (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\EA Replay (Europe) (En,De,Es,It,Nl) (v1.02).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Family Guy (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\FIFA 13 (Netherlands).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\FIFA 14 (Netherlands).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Final Fantasy 2 (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Free Running (Europe) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Ghost in The Shell Stand Alone Complex (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\God of War - Ghost of Sparta (Europe) (En,Pl,Ru) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\God of War Chains of Olympus (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Godfather, The - Mob Wars (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Gran Turismo (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Grand Theft Auto Chinatown Wars (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Grand Theft Auto Chinatown Wars (PSN) (v1.01) [ULUS-10490].iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Grand Theft Auto Liberty City Stories (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Grand theft Auto Liberty City Stories (v2) (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Grand Theft Auto Liberty City Stories (v3) (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Grand Theft Auto Vice City Stories (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\History Channel - Great Battles of Rome (Europe) (En,Fr,De,Es,It) (v1.03).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Juiced 2 - Hot Import Nights (USA) (v1.02).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Juiced Eliminator (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\LEGO Batman (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\LEGO Star Wars II The Original Trilogy (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Loco Roco (USA) [UCUS-98662].iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Loco Roco 2 (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Lord of the Rings Aragorns Quest (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Lumines (Europe) (En,Fr,De,Es,It) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Luxor - Pharaoh's Challenge (Europe) (En,Fr,De,Es,It).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Manhunt 2 (Europe) (En,Fr,De,Es,It) (v1.02).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Marvel - Ultimate Alliance (Europe) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Marvel - Ultimate Alliance 2 (Europe) (v1.02).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Metal Gear Solid Digital Graphic Novel (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Metal Gear Solid Peace Walker (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Miami Vice - The Game (USA) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\MicroMachines V4 (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Midnight Club - L.A. Remix (Europe) (En,Fr,De,Es,It) (v1.03).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Midnight Club 3 - DUB Edition (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Midway Arcade Treasures Extended Play (EUR).ISO.txt"
ECHO . > "G:\Games\PSP\_ISO\Mortal Kombat Unchained (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Mortal Kombat Unchained (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Naruto Shippuden Ultimate Ninja Heroes 3 (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Naruto Shippuden Ultimate Ninja Heroes 3 (USA).ISO.txt"
ECHO . > "G:\Games\PSP\_ISO\Need for Speed - Most Wanted 5-1-0 (Europe) (En,Fr,De,Es,It).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Need for Speed - Undercover (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Need for Speed Underground Rivals (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Obscure The Aftermath.iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Pac Man World 3 (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Pachipara Slot Plus Daiku no Gensan (JAP).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Pac-Man World Rally (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Prince of Persia Rival Swords (EUR).ISO.txt"
ECHO . > "G:\Games\PSP\_ISO\Puzzle Quest - Challenge of the Warlords (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Ridge Racer (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Rock Band Unplugged (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Rocky Balboa (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\R-Type Tactics (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Samurai Warriors - State of War (Europe).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Sega Mega Drive Collection (Europe) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Sega Rally (EUR) RUSSIAN.iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Sega Rally v2 (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Sengoku Musou 3Z Special (Japan) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Smart Bomb (USA) (v1.03).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Sonic Rivals 2 (Europe) (En,Fr,De,Es,It) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Spider-Man 3 (USA) (v1.02).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Star Wars The Force Unleashed (EUR).ISO.txt"
ECHO . > "G:\Games\PSP\_ISO\Street Fighter Alpha 3 MAX (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Syphon Filter - Dark Mirror (Europe) (En,Fr,De,Es,It).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Syphon Filter - Logan's Shadow (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Tekken - Dark Resurrection (USA) (En,Fr,De,Es,It).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Tekken 6 (USA) (En,Fr,De,Es,It,Ru).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Tenchu 4 Shadow Assasins (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\The Simpsons Game (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Tony Hawk's Underground 2 Remix (USA) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Twisted Metal Head On (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\V8 Supercars Australia 2 (Australia) (En,Fr,De,Es,It) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\V8 Supercars Australia 3 - Shootout (Australia) (En,Fr,De,Es,It) (v1.01).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Valhalla Knights 2 (EUR).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Virtua Tennis 3 (Europe) (En,Ja,Fr,De,Es,It).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Warriors Orochi (USA).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Warriors Orochi 2 (USA) (En,Fr) (v1.02).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\WipEout Pulse (USA) (En,Fr,De,Es,It).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\WipEout Pure (USA) (En,Fr,Es) (v1.04).iso.txt"
ECHO . > "G:\Games\PSP\_ISO\Word Puzzle Mojipittan (JAP).ISO.txt"