@ECHO OFF

ECHO Dummy > "G:\Games\PSP\_RIPs\50 Cent - Bulletproof - G-Unit Edition (USA) (v1.02) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Assassin's Creed - Bloodlines (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\B-Boy (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Ben 10 Alien Force (EUR) [ULES-01189] (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Ben 10 Protector of Earth (EUR) [ULES-00906] (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Bomberman (EUR) (v1.02) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Burnout Dominator (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Burnout Legends (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Capcom Classics Collection Reloaded (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Capcom Classics Collection Remixed (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Chessmaster-The Art of Learning (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Coded Arms - Contagion (USA) (v1.04) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Coded Arms (En,Ja) (v1.01) [b] (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Colin McRae - DiRT 2 (USA) (v1.02) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Colin McRae Rally 2005 Plus REPACK (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Dave Mirra BMX Challenge (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Dead to Rights - Reckoning (EUR) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Def Jam - Fight for NY - The Takeover (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Disgaea Infinite (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\DJ MAX Portable 3 (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Driver 76 (EUR) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Dynasty Warriors - Strikeforce (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Dynasty Warriors (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Dynasty Warriors Vol. 2 (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\EA Replay (EUR) (En,De,Es,It,Nl) (v1.02) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Family Guy (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Final Fantasy 2 (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Free Running (EUR) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Ghost in The Shell Stand Alone Complex (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\God of War - Ghost of Sparta (EUR) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\God of War Chains of Olympus (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Godfather, The - Mob Wars (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Gran Turismo (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Grand Theft Auto Chinatown Wars (PSN) (v1.01) [ULUS-10490] (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Grand Theft Auto Liberty City Stories (v3) (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Grand Theft Auto Vice City Stories (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\History Channel - Great Battles of Rome (EUR) (En,Fr,De,Es,It) (v1.03) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Juiced 2 - Hot Import Nights (USA) (v1.02) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Juiced Eliminator (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\LEGO Batman (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\LEGO Star Wars II The Original Trilogy (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Loco Roco (USA) [UCUS-98662] (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Loco Roco 2 (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Lord of the Rings Aragorns Quest (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Lumines (EUR) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Luxor - Pharaoh's Challenge (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Manhunt 2 (EUR) (v1.02) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Marvel - Ultimate Alliance (EUR) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Marvel - Ultimate Alliance 2 (EUR) (v1.02) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Metal Gear Solid Digital Graphic Novel (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Metal Gear Solid Peace Walker (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Miami Vice - The Game (USA) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\MicroMachines V4 (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Midnight Club - L.A. Remix (EUR) (v1.03) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Midnight Club 3 - DUB Edition (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Midway Arcade Treasures Extended Play (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Mortal Kombat Unchained (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Naruto Shippuden Ultimate Ninja Heroes 3 (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Need for Speed - Most Wanted 5-1-0 (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Need for Speed - Undercover (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Need for Speed Underground Rivals (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Obscure The Aftermath (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Pac Man World 3 (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Pachipara Slot Plus Daiku no Gensan (JAP) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Pac-Man World Rally (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Prince of Persia Rival Swords (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Puzzle Quest - Challenge of the Warlords (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Ridge Racer (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Rock Band Unplugged (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Rocky Balboa (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\R-Type Tactics (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Samurai Warriors - State of War (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Sega Mega Drive Collection (EUR) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Sega Rally v2 (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Sengoku Musou 3Z Special (Japan) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Smart Bomb (USA) (v1.03) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Sonic Rivals 2 (EUR) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Spider-Man 3 (USA) (v1.02) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Star Wars The Force Unleashed (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Street Fighter Alpha 3 MAX (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Syphon Filter - Dark Mirror (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Syphon Filter - Logan's Shadow (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Tekken - Dark Resurrection (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Tekken 6 (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Tenchu 4 Shadow Assasins (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\The Simpsons Game (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Tony Hawk's Underground 2 Remix (USA) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Twisted Metal Head On (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\V8 Supercars Australia 2 (AUS) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\V8 Supercars Australia 3 - Shootout (AUS) (v1.01) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Valhalla Knights 2 (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Virtua Tennis 3 (EUR) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Warriors Orochi (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Warriors Orochi 2 (USA) (En,Fr) (v1.02) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\WipEout Pulse (USA) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\WipEout Pure (USA) (v1.04) (ENG Rip by JMD).cso"
ECHO Dummy > "G:\Games\PSP\_RIPs\Word Puzzle Mojipittan (JAP)"